(define (domain satellite)
(:requirements :typing :conditional-effects)
(:types
satellite - object
direction - object
instrument - object
mode - object
)
(:predicates
(leader_turn)
(on_board ?i - instrument ?s - satellite)
(will-be-true-on_board ?i - instrument ?s - satellite)
(will-be-false-on_board ?i - instrument ?s - satellite)
(is-ok-on_board ?i - instrument ?s - satellite)
(supports ?i - instrument ?m - mode)
(will-be-true-supports ?i - instrument ?m - mode)
(will-be-false-supports ?i - instrument ?m - mode)
(is-ok-supports ?i - instrument ?m - mode)
(pointing ?s - satellite ?d - direction)
(will-be-true-pointing ?s - satellite ?d - direction)
(will-be-false-pointing ?s - satellite ?d - direction)
(is-ok-pointing ?s - satellite ?d - direction)
(power_avail ?s - satellite)
(will-be-true-power_avail ?s - satellite)
(will-be-false-power_avail ?s - satellite)
(is-ok-power_avail ?s - satellite)
(power_on ?i - instrument)
(will-be-true-power_on ?i - instrument)
(will-be-false-power_on ?i - instrument)
(is-ok-power_on ?i - instrument)
(calibrated ?i - instrument)
(will-be-true-calibrated ?i - instrument)
(will-be-false-calibrated ?i - instrument)
(is-ok-calibrated ?i - instrument)
(have_image ?d - direction ?m - mode)
(will-be-true-have_image ?d - direction ?m - mode)
(will-be-false-have_image ?d - direction ?m - mode)
(is-ok-have_image ?d - direction ?m - mode)
(calibration_target ?i - instrument ?d - direction)
(will-be-true-calibration_target ?i - instrument ?d - direction)
(will-be-false-calibration_target ?i - instrument ?d - direction)
(is-ok-calibration_target ?i - instrument ?d - direction)
)
(:action fix_turn_to :parameters (?s - satellite ?d_new - direction ?d_prev - direction)
:precondition (and (leader_turn)
(pointing ?s ?d_prev)
)
:effect (and (pointing ?s ?d_new)
(will-be-true-pointing ?s ?d_new)
(not (will-be-false-pointing ?s ?d_new))
(not (pointing ?s ?d_prev))
(will-be-false-pointing ?s ?d_prev)
(not (will-be-true-pointing ?s ?d_prev))
)
)
(:action fix_switch_on :parameters (?i - instrument ?s - satellite)
:precondition (and (leader_turn)
(on_board ?i ?s)
(power_avail ?s)
)
:effect (and (power_on ?i)
(will-be-true-power_on ?i)
(not (will-be-false-power_on ?i))
(not (calibrated ?i))
(will-be-false-calibrated ?i)
(not (will-be-true-calibrated ?i))
(not (power_avail ?s))
(will-be-false-power_avail ?s)
(not (will-be-true-power_avail ?s))
)
)
(:action fix_switch_off :parameters (?i - instrument ?s - satellite)
:precondition (and (leader_turn)
(on_board ?i ?s)
(power_on ?i)
)
:effect (and (not (power_on ?i))
(will-be-false-power_on ?i)
(not (will-be-true-power_on ?i))
(power_avail ?s)
(will-be-true-power_avail ?s)
(not (will-be-false-power_avail ?s))
)
)
(:action fix_calibrate :parameters (?s - satellite ?i - instrument ?d - direction)
:precondition (and (leader_turn)
(on_board ?i ?s)
(calibration_target ?i ?d)
(pointing ?s ?d)
(power_on ?i)
)
:effect (and (calibrated ?i)
(will-be-true-calibrated ?i)
(not (will-be-false-calibrated ?i))
)
)
(:action fix_take_image :parameters (?s - satellite ?d - direction ?i - instrument ?m - mode)
:precondition (and (leader_turn)
(calibrated ?i)
(on_board ?i ?s)
(supports ?i ?m)
(power_on ?i)
(pointing ?s ?d)
)
:effect (and (have_image ?d ?m)
(will-be-true-have_image ?d ?m)
(not (will-be-false-have_image ?d ?m))
)
)
(:action fix_pass_turn_to_follower1 :parameters (?s - satellite ?d_new - direction ?d_prev - direction ?ix3 - instrument)
:precondition (and (leader_turn)
(pointing ?s ?d_prev)
(calibrated ?ix3)
(on_board ?ix3 ?s)
(power_on ?ix3)
(pointing ?s ?d_new)
(pointing ?s ?d_prev)
)
:effect (and (not (leader_turn))
(will-be-true-pointing ?s ?d_new)
(not (will-be-false-pointing ?s ?d_new))
(will-be-false-pointing ?s ?d_prev)
(not (will-be-true-pointing ?s ?d_prev))
(is-ok-pointing ?s ?d_new)
(not (is-ok-pointing ?s ?d_prev))
)
)
(:action fix_pass_turn_to_follower2 :parameters (?s - satellite ?d_new - direction ?d_prev - direction ?ix3 - instrument)
:precondition (and (leader_turn)
(pointing ?s ?d_prev)
(calibrated ?ix3)
(on_board ?ix3 ?s)
(power_on ?ix3)
(pointing ?s ?d_new)
(not (pointing ?s ?d_prev))
)
:effect (and (not (leader_turn))
(will-be-true-pointing ?s ?d_new)
(not (will-be-false-pointing ?s ?d_new))
(will-be-false-pointing ?s ?d_prev)
(not (will-be-true-pointing ?s ?d_prev))
(is-ok-pointing ?s ?d_new)
(is-ok-pointing ?s ?d_prev)
)
)
(:action fix_pass_turn_to_follower3 :parameters (?s - satellite ?d_new - direction ?d_prev - direction ?ix3 - instrument)
:precondition (and (leader_turn)
(pointing ?s ?d_prev)
(calibrated ?ix3)
(on_board ?ix3 ?s)
(power_on ?ix3)
(not (pointing ?s ?d_new))
(pointing ?s ?d_prev)
)
:effect (and (not (leader_turn))
(will-be-true-pointing ?s ?d_new)
(not (will-be-false-pointing ?s ?d_new))
(will-be-false-pointing ?s ?d_prev)
(not (will-be-true-pointing ?s ?d_prev))
(not (is-ok-pointing ?s ?d_new))
(not (is-ok-pointing ?s ?d_prev))
)
)
(:action fix_pass_turn_to_follower4 :parameters (?s - satellite ?d_new - direction ?d_prev - direction ?ix3 - instrument)
:precondition (and (leader_turn)
(pointing ?s ?d_prev)
(calibrated ?ix3)
(on_board ?ix3 ?s)
(power_on ?ix3)
(not (pointing ?s ?d_new))
(not (pointing ?s ?d_prev))
)
:effect (and (not (leader_turn))
(will-be-true-pointing ?s ?d_new)
(not (will-be-false-pointing ?s ?d_new))
(will-be-false-pointing ?s ?d_prev)
(not (will-be-true-pointing ?s ?d_prev))
(not (is-ok-pointing ?s ?d_new))
(is-ok-pointing ?s ?d_prev)
)
)
(:action attack_achieve_goal
:precondition (leader_turn)
:effect (and (is-ok-power_avail satellite0)
(is-ok-power_on instrument0)
(is-ok-power_on instrument1)
(is-ok-calibrated instrument0)
(is-ok-calibrated instrument1)
(is-ok-pointing satellite0 groundstation0)
(is-ok-pointing satellite0 phenomenon2)
(is-ok-pointing satellite0 star1)
(is-ok-pointing satellite0 star3)
(is-ok-have_image star3 image1)
(is-ok-have_image star1 image1)
(is-ok-have_image phenomenon2 image1)
(is-ok-have_image groundstation0 image1)
(is-ok-have_image star3 thermograph0)
(is-ok-have_image star1 thermograph0)
(is-ok-have_image phenomenon2 thermograph0)
(is-ok-have_image groundstation0 thermograph0)
)
)
(:action attack_turn_to1 :parameters (?s - satellite ?d_new - direction ?d_prev - direction)
:precondition (and (not (leader_turn)) (not (= ?d_prev ?d_new))
(pointing ?s ?d_prev)
(will-be-false-pointing ?s ?d_new)
(will-be-false-pointing ?s ?d_prev)
)
:effect (and (pointing ?s ?d_new)
(not (pointing ?s ?d_prev))
(not (is-ok-pointing ?s ?d_new))
(is-ok-pointing ?s ?d_prev)
)
)
(:action attack_turn_to2 :parameters (?s - satellite ?d_new - direction ?d_prev - direction)
:precondition (and (not (leader_turn)) (= ?d_prev ?d_new)
(pointing ?s ?d_prev)
(will-be-false-pointing ?s ?d_new)
(will-be-false-pointing ?s ?d_prev)
)
:effect (and (pointing ?s ?d_new)
(not (pointing ?s ?d_prev))
(not (is-ok-pointing ?s ?d_new))
)
)
(:action attack_turn_to3 :parameters (?s - satellite ?d_new - direction ?d_prev - direction)
:precondition (and (not (leader_turn)) (pointing ?s ?d_prev)
(will-be-false-pointing ?s ?d_new)
(will-be-true-pointing ?s ?d_prev)
)
:effect (and (pointing ?s ?d_new)
(not (pointing ?s ?d_prev))
(not (is-ok-pointing ?s ?d_new))
(not (is-ok-pointing ?s ?d_prev))
)
)
(:action attack_turn_to4 :parameters (?s - satellite ?d_new - direction ?d_prev - direction)
:precondition (and (not (leader_turn)) (pointing ?s ?d_prev)
(will-be-true-pointing ?s ?d_new)
(will-be-false-pointing ?s ?d_prev)
)
:effect (and (pointing ?s ?d_new)
(not (pointing ?s ?d_prev))
(is-ok-pointing ?s ?d_new)
(is-ok-pointing ?s ?d_prev)
)
)
(:action attack_turn_to5 :parameters (?s - satellite ?d_new - direction ?d_prev - direction)
:precondition (and (not (leader_turn)) (pointing ?s ?d_prev)
(will-be-true-pointing ?s ?d_new)
(will-be-true-pointing ?s ?d_prev)
)
:effect (and (pointing ?s ?d_new)
(not (pointing ?s ?d_prev))
(is-ok-pointing ?s ?d_new)
(not (is-ok-pointing ?s ?d_prev))
)
)
(:action attack_switch_on1 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_avail ?s)
(will-be-false-power_on ?i)
(will-be-false-calibrated ?i)
(will-be-false-power_avail ?s)
)
:effect (and (power_on ?i)
(not (calibrated ?i))
(not (power_avail ?s))
(not (is-ok-power_on ?i))
(is-ok-calibrated ?i)
(is-ok-power_avail ?s)
)
)
(:action attack_switch_on2 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_avail ?s)
(will-be-false-power_on ?i)
(will-be-false-calibrated ?i)
(will-be-true-power_avail ?s)
)
:effect (and (power_on ?i)
(not (calibrated ?i))
(not (power_avail ?s))
(not (is-ok-power_on ?i))
(is-ok-calibrated ?i)
(not (is-ok-power_avail ?s))
)
)
(:action attack_switch_on3 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_avail ?s)
(will-be-false-power_on ?i)
(will-be-true-calibrated ?i)
(will-be-false-power_avail ?s)
)
:effect (and (power_on ?i)
(not (calibrated ?i))
(not (power_avail ?s))
(not (is-ok-power_on ?i))
(not (is-ok-calibrated ?i))
(is-ok-power_avail ?s)
)
)
(:action attack_switch_on4 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_avail ?s)
(will-be-false-power_on ?i)
(will-be-true-calibrated ?i)
(will-be-true-power_avail ?s)
)
:effect (and (power_on ?i)
(not (calibrated ?i))
(not (power_avail ?s))
(not (is-ok-power_on ?i))
(not (is-ok-calibrated ?i))
(not (is-ok-power_avail ?s))
)
)
(:action attack_switch_on5 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_avail ?s)
(will-be-true-power_on ?i)
(will-be-false-calibrated ?i)
(will-be-false-power_avail ?s)
)
:effect (and (power_on ?i)
(not (calibrated ?i))
(not (power_avail ?s))
(is-ok-power_on ?i)
(is-ok-calibrated ?i)
(is-ok-power_avail ?s)
)
)
(:action attack_switch_on6 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_avail ?s)
(will-be-true-power_on ?i)
(will-be-false-calibrated ?i)
(will-be-true-power_avail ?s)
)
:effect (and (power_on ?i)
(not (calibrated ?i))
(not (power_avail ?s))
(is-ok-power_on ?i)
(is-ok-calibrated ?i)
(not (is-ok-power_avail ?s))
)
)
(:action attack_switch_on7 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_avail ?s)
(will-be-true-power_on ?i)
(will-be-true-calibrated ?i)
(will-be-false-power_avail ?s)
)
:effect (and (power_on ?i)
(not (calibrated ?i))
(not (power_avail ?s))
(is-ok-power_on ?i)
(not (is-ok-calibrated ?i))
(is-ok-power_avail ?s)
)
)
(:action attack_switch_on8 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_avail ?s)
(will-be-true-power_on ?i)
(will-be-true-calibrated ?i)
(will-be-true-power_avail ?s)
)
:effect (and (power_on ?i)
(not (calibrated ?i))
(not (power_avail ?s))
(is-ok-power_on ?i)
(not (is-ok-calibrated ?i))
(not (is-ok-power_avail ?s))
)
)
(:action attack_switch_off1 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_on ?i)
(will-be-false-power_on ?i)
(will-be-false-power_avail ?s)
)
:effect (and (not (power_on ?i))
(power_avail ?s)
(is-ok-power_on ?i)
(not (is-ok-power_avail ?s))
)
)
(:action attack_switch_off2 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_on ?i)
(will-be-false-power_on ?i)
(will-be-true-power_avail ?s)
)
:effect (and (not (power_on ?i))
(power_avail ?s)
(is-ok-power_on ?i)
(is-ok-power_avail ?s)
)
)
(:action attack_switch_off3 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_on ?i)
(will-be-true-power_on ?i)
(will-be-false-power_avail ?s)
)
:effect (and (not (power_on ?i))
(power_avail ?s)
(not (is-ok-power_on ?i))
(not (is-ok-power_avail ?s))
)
)
(:action attack_switch_off4 :parameters (?i - instrument ?s - satellite)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(power_on ?i)
(will-be-true-power_on ?i)
(will-be-true-power_avail ?s)
)
:effect (and (not (power_on ?i))
(power_avail ?s)
(not (is-ok-power_on ?i))
(is-ok-power_avail ?s)
)
)
(:action attack_calibrate1 :parameters (?s - satellite ?i - instrument ?d - direction)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(calibration_target ?i ?d)
(pointing ?s ?d)
(power_on ?i)
(will-be-false-calibrated ?i)
)
:effect (and (calibrated ?i)
(not (is-ok-calibrated ?i))
)
)
(:action attack_calibrate2 :parameters (?s - satellite ?i - instrument ?d - direction)
:precondition (and (not (leader_turn)) (on_board ?i ?s)
(calibration_target ?i ?d)
(pointing ?s ?d)
(power_on ?i)
(will-be-true-calibrated ?i)
)
:effect (and (calibrated ?i)
(is-ok-calibrated ?i)
)
)
(:action attack_take_image1 :parameters (?s - satellite ?d - direction ?i - instrument ?m - mode)
:precondition (and (not (leader_turn)) (calibrated ?i)
(on_board ?i ?s)
(supports ?i ?m)
(power_on ?i)
(pointing ?s ?d)
(will-be-false-have_image ?d ?m)
)
:effect (and (have_image ?d ?m)
(not (is-ok-have_image ?d ?m))
)
)
(:action attack_take_image2 :parameters (?s - satellite ?d - direction ?i - instrument ?m - mode)
:precondition (and (not (leader_turn)) (calibrated ?i)
(on_board ?i ?s)
(supports ?i ?m)
(power_on ?i)
(pointing ?s ?d)
(will-be-true-have_image ?d ?m)
)
:effect (and (have_image ?d ?m)
(is-ok-have_image ?d ?m)
)
)
)
