(define
	(problem strips-gripper-x-1)

	(:domain gripper-strips)

	(:objects
		rooma
		roomb
		ball4
		ball3
		ball2
		ball1
		left
		right
	)

	(:init
		(room rooma)
		(room roomb)
		(ball ball4)
		(ball ball3)
		(ball ball2)
		(ball ball1)
		(at-robby rooma)
		(free left)
		(free right)
		(at ball4 rooma)
		(at ball3 rooma)
		(at ball2 rooma)
		(at ball1 rooma)
		(gripper left)
		(gripper right)
		(leader-state-at-robby rooma)
		(leader-state-free left)
		(leader-state-free right)
		(leader-state-at ball4 rooma)
		(leader-state-at ball3 rooma)
		(leader-state-at ball2 rooma)
		(leader-state-at ball1 rooma)
		(is-goal-at-robby rooma)
		(is-goal-free left)
		(is-goal-free right)
		(is-goal-at ball4 rooma)
		(is-goal-at ball3 rooma)
		(is-goal-at ball2 rooma)
		(is-goal-at ball1 rooma)
		(leader-turn)
	)

	(:goal
		(and
			(room rooma)
			(room roomb)
			(room ball4)
			(room ball3)
			(room ball2)
			(room ball1)
			(room left)
			(room right)
			(ball rooma)
			(ball roomb)
			(ball ball4)
			(ball ball3)
			(ball ball2)
			(ball ball1)
			(ball left)
			(ball right)
			(gripper rooma)
			(gripper roomb)
			(gripper ball4)
			(gripper ball3)
			(gripper ball2)
			(gripper ball1)
			(gripper left)
			(gripper right)
			(is-goal-at-robby rooma)
			(is-goal-at-robby roomb)
			(is-goal-at-robby ball4)
			(is-goal-at-robby ball3)
			(is-goal-at-robby ball2)
			(is-goal-at-robby ball1)
			(is-goal-at-robby left)
			(is-goal-at-robby right)
			(is-goal-at rooma rooma)
			(is-goal-at rooma roomb)
			(is-goal-at rooma ball4)
			(is-goal-at rooma ball3)
			(is-goal-at rooma ball2)
			(is-goal-at rooma ball1)
			(is-goal-at rooma left)
			(is-goal-at rooma right)
			(is-goal-at roomb rooma)
			(is-goal-at roomb roomb)
			(is-goal-at roomb ball4)
			(is-goal-at roomb ball3)
			(is-goal-at roomb ball2)
			(is-goal-at roomb ball1)
			(is-goal-at roomb left)
			(is-goal-at roomb right)
			(is-goal-at ball4 rooma)
			(is-goal-at ball4 roomb)
			(is-goal-at ball4 ball4)
			(is-goal-at ball4 ball3)
			(is-goal-at ball4 ball2)
			(is-goal-at ball4 ball1)
			(is-goal-at ball4 left)
			(is-goal-at ball4 right)
			(is-goal-at ball3 rooma)
			(is-goal-at ball3 roomb)
			(is-goal-at ball3 ball4)
			(is-goal-at ball3 ball3)
			(is-goal-at ball3 ball2)
			(is-goal-at ball3 ball1)
			(is-goal-at ball3 left)
			(is-goal-at ball3 right)
			(is-goal-at ball2 rooma)
			(is-goal-at ball2 roomb)
			(is-goal-at ball2 ball4)
			(is-goal-at ball2 ball3)
			(is-goal-at ball2 ball2)
			(is-goal-at ball2 ball1)
			(is-goal-at ball2 left)
			(is-goal-at ball2 right)
			(is-goal-at ball1 rooma)
			(is-goal-at ball1 roomb)
			(is-goal-at ball1 ball4)
			(is-goal-at ball1 ball3)
			(is-goal-at ball1 ball2)
			(is-goal-at ball1 ball1)
			(is-goal-at ball1 left)
			(is-goal-at ball1 right)
			(is-goal-at left rooma)
			(is-goal-at left roomb)
			(is-goal-at left ball4)
			(is-goal-at left ball3)
			(is-goal-at left ball2)
			(is-goal-at left ball1)
			(is-goal-at left left)
			(is-goal-at left right)
			(is-goal-at right rooma)
			(is-goal-at right roomb)
			(is-goal-at right ball4)
			(is-goal-at right ball3)
			(is-goal-at right ball2)
			(is-goal-at right ball1)
			(is-goal-at right left)
			(is-goal-at right right)
			(is-goal-free rooma)
			(is-goal-free roomb)
			(is-goal-free ball4)
			(is-goal-free ball3)
			(is-goal-free ball2)
			(is-goal-free ball1)
			(is-goal-free left)
			(is-goal-free right)
			(is-goal-carry rooma rooma)
			(is-goal-carry rooma roomb)
			(is-goal-carry rooma ball4)
			(is-goal-carry rooma ball3)
			(is-goal-carry rooma ball2)
			(is-goal-carry rooma ball1)
			(is-goal-carry rooma left)
			(is-goal-carry rooma right)
			(is-goal-carry roomb rooma)
			(is-goal-carry roomb roomb)
			(is-goal-carry roomb ball4)
			(is-goal-carry roomb ball3)
			(is-goal-carry roomb ball2)
			(is-goal-carry roomb ball1)
			(is-goal-carry roomb left)
			(is-goal-carry roomb right)
			(is-goal-carry ball4 rooma)
			(is-goal-carry ball4 roomb)
			(is-goal-carry ball4 ball4)
			(is-goal-carry ball4 ball3)
			(is-goal-carry ball4 ball2)
			(is-goal-carry ball4 ball1)
			(is-goal-carry ball4 left)
			(is-goal-carry ball4 right)
			(is-goal-carry ball3 rooma)
			(is-goal-carry ball3 roomb)
			(is-goal-carry ball3 ball4)
			(is-goal-carry ball3 ball3)
			(is-goal-carry ball3 ball2)
			(is-goal-carry ball3 ball1)
			(is-goal-carry ball3 left)
			(is-goal-carry ball3 right)
			(is-goal-carry ball2 rooma)
			(is-goal-carry ball2 roomb)
			(is-goal-carry ball2 ball4)
			(is-goal-carry ball2 ball3)
			(is-goal-carry ball2 ball2)
			(is-goal-carry ball2 ball1)
			(is-goal-carry ball2 left)
			(is-goal-carry ball2 right)
			(is-goal-carry ball1 rooma)
			(is-goal-carry ball1 roomb)
			(is-goal-carry ball1 ball4)
			(is-goal-carry ball1 ball3)
			(is-goal-carry ball1 ball2)
			(is-goal-carry ball1 ball1)
			(is-goal-carry ball1 left)
			(is-goal-carry ball1 right)
			(is-goal-carry left rooma)
			(is-goal-carry left roomb)
			(is-goal-carry left ball4)
			(is-goal-carry left ball3)
			(is-goal-carry left ball2)
			(is-goal-carry left ball1)
			(is-goal-carry left left)
			(is-goal-carry left right)
			(is-goal-carry right rooma)
			(is-goal-carry right roomb)
			(is-goal-carry right ball4)
			(is-goal-carry right ball3)
			(is-goal-carry right ball2)
			(is-goal-carry right ball1)
			(is-goal-carry right left)
			(is-goal-carry right right)
		)
	)

)
