(define (problem strips-sat-x-1)
(:domain satellite)
(:objects satellite0 - satellite instrument0 - instrument instrument1 - instrument image1 - mode thermograph0 - mode star1 - direction groundstation0 - direction phenomenon2 - direction star3 - direction)
(:init (leader_turn)
(calibration_target instrument0 groundstation0)
(will-be-true-calibration_target instrument0 groundstation0)
(is-ok-calibration_target instrument0 groundstation0)
(supports instrument1 thermograph0)
(will-be-true-supports instrument1 thermograph0)
(is-ok-supports instrument1 thermograph0)
(calibration_target instrument1 groundstation0)
(will-be-true-calibration_target instrument1 groundstation0)
(is-ok-calibration_target instrument1 groundstation0)
(supports instrument0 thermograph0)
(will-be-true-supports instrument0 thermograph0)
(is-ok-supports instrument0 thermograph0)
(supports instrument1 image1)
(will-be-true-supports instrument1 image1)
(is-ok-supports instrument1 image1)
(on_board instrument0 satellite0)
(will-be-true-on_board instrument0 satellite0)
(is-ok-on_board instrument0 satellite0)
(on_board instrument1 satellite0)
(will-be-true-on_board instrument1 satellite0)
(is-ok-on_board instrument1 satellite0)
(power_avail satellite0)
(will-be-true-power_avail satellite0)
(is-ok-power_avail satellite0)
(will-be-false-power_on instrument0)
(is-ok-power_on instrument0)
(will-be-false-power_on instrument1)
(is-ok-power_on instrument1)
(will-be-false-calibrated instrument0)
(is-ok-calibrated instrument0)
(will-be-false-calibrated instrument1)
(is-ok-calibrated instrument1)
(pointing satellite0 groundstation0)
(will-be-true-pointing satellite0 groundstation0)
(is-ok-pointing satellite0 groundstation0)
(will-be-false-pointing satellite0 phenomenon2)
(is-ok-pointing satellite0 phenomenon2)
(will-be-false-pointing satellite0 star1)
(is-ok-pointing satellite0 star1)
(will-be-false-pointing satellite0 star3)
(is-ok-pointing satellite0 star3)
(will-be-false-have_image star3 image1)
(is-ok-have_image star3 image1)
(will-be-false-have_image star1 image1)
(is-ok-have_image star1 image1)
(will-be-false-have_image phenomenon2 image1)
(is-ok-have_image phenomenon2 image1)
(will-be-false-have_image groundstation0 image1)
(is-ok-have_image groundstation0 image1)
(will-be-false-have_image star3 thermograph0)
(is-ok-have_image star3 thermograph0)
(will-be-false-have_image star1 thermograph0)
(is-ok-have_image star1 thermograph0)
(will-be-false-have_image phenomenon2 thermograph0)
(is-ok-have_image phenomenon2 thermograph0)
(will-be-false-have_image groundstation0 thermograph0)
(is-ok-have_image groundstation0 thermograph0)
)
(:goal (and (is-ok-power_avail satellite0)
(is-ok-power_on instrument0)
(is-ok-power_on instrument1)
(is-ok-calibrated instrument0)
(is-ok-calibrated instrument1)
(is-ok-pointing satellite0 groundstation0)
(is-ok-pointing satellite0 phenomenon2)
(is-ok-pointing satellite0 star1)
(is-ok-pointing satellite0 star3)
(is-ok-have_image star3 image1)
(is-ok-have_image star1 image1)
(is-ok-have_image phenomenon2 image1)
(is-ok-have_image groundstation0 image1)
(is-ok-have_image star3 thermograph0)
(is-ok-have_image star1 thermograph0)
(is-ok-have_image phenomenon2 thermograph0)
(is-ok-have_image groundstation0 thermograph0)
)
)
)
