use std::{ffi::OsString, fs, os::unix::prelude::OpenOptionsExt, path::PathBuf};

pub fn generate_script(fastdownward_path: &PathBuf, script_path: &PathBuf) {
    let content = format!(
        "
        #!/bin/bash
        # DO NOT EDIT. THIS AUTO GENERATED BY SOMEONE WHO DOESN'T KNOW HOW THIS
        # STUFF WORKS. IT MIGHT CAUSE AN EXPLOSION IN AN URBAN VILLAGE FOR SOME
        # REASON. I MEAN, I DON*T THINK IT WILL. BUT HOW CAN ONE TRULY KNOW?

        dir=`echo lama-$1 | sed 's/\\//-/g'`
        mkdir $dir
        cd $dir

        p1=$1

        if [ ${{p1:0:1}} == \"/\" ]
        then
            p2=$2
            p3=$3
        else
            p1=\"../$1\"
            p2=\"../$2\"
            p3=\"../$3\"
        fi
        
        python3 {} --alias lama-first --plan-file plan.soln $p1 $p2
        
        mv -T plan.soln $p3
       
        rm *

        cd ..
        rmdir $dir
        ",
        fs::canonicalize(fastdownward_path)
            .unwrap()
            .to_str()
            .unwrap()
    );
    let _ = fs::remove_file(script_path);
    let _ = fs::OpenOptions::new()
        .create(true)
        .write(true)
        .mode(0o770)
        .open(script_path)
        .unwrap();
    let _ = fs::write(script_path, content);
}
